server:
  port: 8080
spring:
  application:
    name: api-gateway
    gateway:
      routes:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/