server:
  port: 8080
spring:
  application:
    name: api-gateway
#  data:
#    redis:
#      database: 0
#      host: localhost
#      port: 6379
#      timeout: 60000
  cloud:
    gateway:
#      filter:
#        local-response-cache:
#          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/account/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuitBreakerInstance
                fallbackUri: forward:/fallback/user
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                redis-rate-limiter.requestedTokens: 1
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/delivery/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuitBreakerInstance
                fallbackUri: forward:/fallback/delivery
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                redis-rate-limiter.requestedTokens: 1
        - id: parcel-service
          uri: lb://parcel-service
          predicates:
            - Path=/api/v1/parcel/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuitBreakerInstance
                fallbackUri: forward:/fallback/parcel
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                redis-rate-limiter.requestedTokens: 1
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true