server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/**
            - Path=/swagger-ui/index.html#/
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/**
            - Path=/swagger-ui/index.html#/
        - id: parcel-service
          uri: lb://parcel-service
          predicates:
            - Path=/api/v1/**
            - Path=/swagger-ui/index.html#/
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true