server:
  port: 8083
spring:
  application:
    name: delivery-service
  data:
    mongodb:
      uri: mongodb://mongodb-parcel/delivery
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
jwt:
  secret: 6D597133743677397A24432646294A404E635166546A576E5A72347537782141
  token:
    expiration: 3600000
management:
  endpoints:
    web:
      exposure:
        include: '*'
#  instance:
#    prefer-ip-address: true