server:
  port: 8083
spring:
  application:
    name: delivery-service
  data:
    mongodb:
      uri: mongodb://mongodb-parcel/delivery
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
#  instance:
#    prefer-ip-address: true