server:
  port: 8081
spring:
  application:
    name: user-service
  data:
    redis:
#      database: 0
      host: redis
      port: 6379
      timeout: 60000
  cache:
    type: redis
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
  liquibase:
    enabled: true
    liquibase-schema: migration_schema
    default-schema: auth_schema
jwt:
  secret: 6D597133743677397A24432646294A404E635166546A576E5A72347537782141
  token:
    expiration: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
#  instance:
#    prefer-ip-address: true
